/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KalendarzRouteImport } from './routes/kalendarz'
import { Route as PozycjeRouteImport } from './routes/pozycje'
import { Route as UstawieniaRouteImport } from './routes/ustawienia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KalendarzRoute = KalendarzRouteImport.update({
  id: '/kalendarz',
  path: '/kalendarz',
  getParentRoute: () => rootRouteImport,
} as any)
const PozycjeRoute = PozycjeRouteImport.update({
  id: '/pozycje',
  path: '/pozycje',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaRoute = UstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kalendarz': typeof KalendarzRoute
  '/pozycje': typeof PozycjeRoute
  '/ustawienia': typeof UstawieniaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kalendarz': typeof KalendarzRoute
  '/pozycje': typeof PozycjeRoute
  '/ustawienia': typeof UstawieniaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kalendarz': typeof KalendarzRoute
  '/pozycje': typeof PozycjeRoute
  '/ustawienia': typeof UstawieniaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/kalendarz' | '/pozycje' | '/ustawienia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/kalendarz' | '/pozycje' | '/ustawienia'
  id: '__root__' | '/' | '/auth' | '/kalendarz' | '/pozycje' | '/ustawienia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  KalendarzRoute: typeof KalendarzRoute
  PozycjeRoute: typeof PozycjeRoute
  UstawieniaRoute: typeof UstawieniaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalendarz': {
      id: '/kalendarz'
      path: '/kalendarz'
      fullPath: '/kalendarz'
      preLoaderRoute: typeof KalendarzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pozycje': {
      id: '/pozycje'
      path: '/pozycje'
      fullPath: '/pozycje'
      preLoaderRoute: typeof PozycjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia': {
      id: '/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof UstawieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  KalendarzRoute: KalendarzRoute,
  PozycjeRoute: PozycjeRoute,
  UstawieniaRoute: UstawieniaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
