/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KalendarzRouteImport } from './routes/kalendarz'
import { Route as PozycjeRouteImport } from './routes/pozycje'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PrywatnoscRouteImport } from './routes/prywatnosc'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as UstawieniaRouteImport } from './routes/ustawienia'
import { Route as ZwrotyRouteImport } from './routes/zwroty'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KalendarzRoute = KalendarzRouteImport.update({
  id: '/kalendarz',
  path: '/kalendarz',
  getParentRoute: () => rootRouteImport,
} as any)
const PozycjeRoute = PozycjeRouteImport.update({
  id: '/pozycje',
  path: '/pozycje',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrywatnoscRoute = PrywatnoscRouteImport.update({
  id: '/prywatnosc',
  path: '/prywatnosc',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaRoute = UstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => rootRouteImport,
} as any)
const ZwrotyRoute = ZwrotyRouteImport.update({
  id: '/zwroty',
  path: '/zwroty',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kalendarz': typeof KalendarzRoute
  '/pozycje': typeof PozycjeRoute
  '/pro': typeof ProRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/ustawienia': typeof UstawieniaRoute
  '/zwroty': typeof ZwrotyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kalendarz': typeof KalendarzRoute
  '/pozycje': typeof PozycjeRoute
  '/pro': typeof ProRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/ustawienia': typeof UstawieniaRoute
  '/zwroty': typeof ZwrotyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kalendarz': typeof KalendarzRoute
  '/pozycje': typeof PozycjeRoute
  '/pro': typeof ProRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/ustawienia': typeof UstawieniaRoute
  '/zwroty': typeof ZwrotyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kalendarz'
    | '/pozycje'
    | '/pro'
    | '/prywatnosc'
    | '/regulamin'
    | '/ustawienia'
    | '/zwroty'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kalendarz'
    | '/pozycje'
    | '/pro'
    | '/prywatnosc'
    | '/regulamin'
    | '/ustawienia'
    | '/zwroty'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/kalendarz'
    | '/pozycje'
    | '/pro'
    | '/prywatnosc'
    | '/regulamin'
    | '/ustawienia'
    | '/zwroty'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  KalendarzRoute: typeof KalendarzRoute
  PozycjeRoute: typeof PozycjeRoute
  ProRoute: typeof ProRoute
  PrywatnoscRoute: typeof PrywatnoscRoute
  RegulaminRoute: typeof RegulaminRoute
  UstawieniaRoute: typeof UstawieniaRoute
  ZwrotyRoute: typeof ZwrotyRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalendarz': {
      id: '/kalendarz'
      path: '/kalendarz'
      fullPath: '/kalendarz'
      preLoaderRoute: typeof KalendarzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pozycje': {
      id: '/pozycje'
      path: '/pozycje'
      fullPath: '/pozycje'
      preLoaderRoute: typeof PozycjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prywatnosc': {
      id: '/prywatnosc'
      path: '/prywatnosc'
      fullPath: '/prywatnosc'
      preLoaderRoute: typeof PrywatnoscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia': {
      id: '/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof UstawieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zwroty': {
      id: '/zwroty'
      path: '/zwroty'
      fullPath: '/zwroty'
      preLoaderRoute: typeof ZwrotyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  KalendarzRoute: KalendarzRoute,
  PozycjeRoute: PozycjeRoute,
  ProRoute: ProRoute,
  PrywatnoscRoute: PrywatnoscRoute,
  RegulaminRoute: RegulaminRoute,
  UstawieniaRoute: UstawieniaRoute,
  ZwrotyRoute: ZwrotyRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
